- .gitignore
- test_shell.py
- tests/test_test_shell.py
- test_shell 스켈레톤 코드 생성
- test_shell 테스트 코드 생성(스켈레톤)
- test_shell 각 기능 개발을 위해서 스켈레톤 코드를 생성했습니다.
- 모두 통과하는 테스트만 있습니다(test_test_shell.py)
> feature: test_shell init

- .gitignore
- .gitignore 를 수정하였습니다.
- 불필요한 화일 upload 방지
- None
- None
> .gitignore 를 update 하였습니다

- ssd.py
- read/write에 파일 생성 기능을 추가하였습니다.
- 테스트 케이스에서 확인을 위해 파일 생성이 필요합니다.
- TC Pass(TC 생성 전
> SSD read/write file creation

- test_shell.py
- tests/test_test_shell.py
- import module path수정 및 help method 수정
- 경로가 달라 error 발생
- python 버전이 달라서 error 발생으로 help method 수정 
- test_shell_help 테스트 확인
> [bugFix] fix import module path and help method

- test_shell.py
- tests/test_test_shell.py
-  shell을 이용한 write의 기본 테스트를 추가했습니다.
- 올바른 주소에 값을 write했을때 리턴을 추가했고, mocking을 이용해 서브 프로세스가 동작하는지 확인했습니다.
- subprocess를 통해 ssd를 콜하는 것이 지금 올린것처럼 수행하면 될지 논의가 필요합니다.
> [feature] add Implementation and test for basic shell write

- ssd.py
- string lba에 대해 문제 해결을 위한 예외처리
- 'A' 처럼 string lba가 들어왔을때 숫자와 비교가 불가해서 런타임 에러가 발생함
- test_read_invalid_lba_error 테스트 통과
> [feature] add string lba error guard

- shell.py
- tests/test_shell.py
- full read 기능 추가
- spec 구현
- read 동작 return 확인 및 call 100회 확인
> [feature] add full_read function

- shell.py
- tests/test_shell.py
- 초기작성한 코드의 refactoring을 수행하였습니다.
- 기존 작성한 테스트를 모두 통과하는지 확인했습니다.
> [refactor] Refactor shell and test_shell 

- shell.py
- tests/test_shell.py
- cmd를 파싱하고, 함수를 수행하는 코드가 복잡하여 extract method를 적용했습다.
- 기존 테스트케이스로 테스트 했습니다.
> [refactoring] add process_cmd to process commands in shell

- shell.py
- tests/test_shell.py
- test-script spec 구현
- 
- test-script spec에 맞게 테스트 
-
> [feature] add test-script spec

- shell.py
- help 함수에 추가된 기능 설명 추가
- help 출력
> [refactoring] add function in help

- ssd.py
- [FIXED] git rebase 문제를 해결하였습니다. rebase 시 수정된 write 함수가 test_ssd_write 테스트를 통해 정상작동함을 확인하였습니다.
- [FIXED] ssd.py write function 의 _write_output 을 제거하였습니다
- (optional)
- test_ssd_write.py
- (optional)
> [FIXED] git rebase 문제 해결 및 write function fix (_write_output)

- tests/test_shell.py
- help에 추가된 내용을 test시 체크하도록 수정
- help에 추가된 내용을 test시 체크하도록 수정
- test_shell_help 테스트 시 pass 확인
> [bugFix] add expected command

- command.py
- ssd.py
- Command Pattern을 적용하였습니다. (로컬 txt 파일은 생성 전입니다.)
- 향후 명령어 추가 시 확장성을 확보하기 위해 수정하였습니다.
- test_ssd.py 로 동작하는 것을 확인하였습니다.
- 
- 커맨드 패턴이 잘 적용되었는지 확인 부탁드립니다.
> [Refactor] Command Pattern 추가

- tests/test_ssd_write.py
- [FIXED] test_write_out_of_range_lba_error, test_write_invalid_lba_error, test_write_success_lba99 (optional) 추가하였습니다
- (optional)
- NA
- (optional)
> [FIXED] rebase 후 test_ssd_write.py 에 invalid address, invalid value 검사 항목 추가 및 확인 완료

- file_handler.py
- ssd.py
- tests/test_read.py
📌 변경 내용
ssd에 singletone 패턴 적용
ssd에서 singletone 패턴 적용으로 init 함수가 매번 돌지 않기 때문에 매 테스트 마다 ssd의 init 함수가 돌도록 테스트 코드 수정
file 처리를 위해서 기본 읽기 쓰기가 있는 SimpleFileHandler class와 decorator 패턴으로 파일 전체 읽기, 특정 라인 읽기, 쓰기 기능을 추가한 MultilineFileWriter를 추가
🔍 변경 이유
SSD를 init마다 함수가 돌지 않도록 하기 위해 SSD에 initialized 속성이 생기면 더 이상 SSD() 선언해도 init 함수가 돌지 않도록 수정
반복된 file read write 기능의 책임을 별도 클래스로 분기하고, 그 중에서 가장 기본만 하는 클래스와 멀티 라인을 커버할 수 있는 좀 더 복잡한 기능을 수행하는 클래스를 생성
🧪 테스트 방법
기존의 read write test 수행
⚠️ 리뷰 시 중점적으로 볼 부분
특정 구현, 논의가 필요한 부분 등(optional)
> [refactor] decorator 패턴을 적용한 file handler 적용

- tests/test_shell.py
- 새로 추가한 erase에 대한 네거티브 테스트 추가했습니다.
> [feature] Add negative tests for erase

- ssd.py
> [feature] check target validation in SSD

- shell.py
- shell_cmd_checker.py
- ssd_driver.py
- tests/test_shell.py
- Shell.py 모듈이 커져서 용도와 객체별로 좀 구분하였습니다
- ssd_driver.py / shell_cmd_checker.py로 분리
- 일부 중복 부분 function extract해서 정리하였습니다.
- 리팩토링하여 코드 구조화 및 가독성 향상
- 기존 테스트 통과 확인.
- Shell 동작이나 기존 동작에 영향가는 부분있는지 체크해주시면 감사하겠습니다!
> [Refactor] shell clean up

- tests/test_logger.py
- logger에서 set_formatter 기능에 대한 테스트 케이스를 추가했습니다.
- test coverage를 최대한 끌어올리기 위해서 추가했습니다.
> test: add test for set_formatter in logger

- logger.py
- shell.py
- shell_cmd_checker.py
- ssd_driver.py
- utils.py
- test-shell-app에 로깅을 추가했습니다.
- 원활한 디버깅을 위해서 로깅이 필요합니다.
> feature: add log for test-shell-app

- ssd.py
- buffer 파일 생성이 되지 않는 버그를 수정했습니다.
> [refactor] Remove wrong override in command buffer class

- command.py
- tests/test_buffer.py
- command 구성 변경에 따른 테스트 코드 수정
- Invoker 변경에 따른 테스트 코드 수정
- test_buffer 테스트 수행
> [test] add command buffer test

- ssd.py
- tests/test_cmd_buffer_ignore_cmd.py
- ignore cmd 알고리즘 구현 정리, TC 추가 
- 관련 TC 추가하여 통과 확인
> [Feature] cmd buffer opt ignore cmd

- tests/test_buffer_fastread.py
- fastread test 초안 (ssd 기능 구현에 맞춰 수정 필요)
- pytest
> init fastread test

- tests/test_fast_read.py
- [FIXED] teset_fast_read.py minor fix - directory, files 맞춤
- (optional)
- 모든 TC 에 대해 passed
- (optional)
> [FIXED] teset_fast_read.py - minior fix
